# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab5c5d583e2531fd4035da8925c87b0e344b2bfb396347bea04a5e344c64e0e9653f179ef028950dcebc858a404a94e243fb00b812a1303c7de73b3d37d19a5

test:
  secret_key_base: 2a5f5778a055945cb1f98eca44c1e05a740ca9061b9875a9799015f56f031ef3f718fb10949eac7644e8fb47ab8521018d7e2e4d3e6970ff38c68e13aeebef29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
